server:
  port: 8888

mybatis:
  #config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: boot.spring.po

spring:
  datasource:
    url: jdbc:mysql://localhost/activiti?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/
    history-level: full
  thymeleaf:
    mode: LEGACYHTML5

logging:
  config: classpath:logback-spring.xml